spring.application.name=ai-chatbot

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3.2

spring.datasource.url=jdbc:postgresql://localhost:5432/springai
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.ai.chat.memory.repository.jdbc.initialize-schema=always