version: '3.8'

services:
  acme-api:
    container_name: acme-api
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://acme-db:5432/acme_db
      - SPRING_DATASOURCE_USERNAME=acme_admin_user
      - SPRING_DATASOURCE_PASSWORD=acme_admin_pwd
    networks:
      - acme-network

networks:
   acme-network:
      external: true
