package br.com.joaofelipefaria.ai.springai.controller;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import br.com.joaofelipefaria.ai.springai.dto.ChatRequest;
import br.com.joaofelipefaria.ai.springai.dto.ChatResponse;
import br.com.joaofelipefaria.ai.springai.service.ChatService;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;

/**
 * Exposes chat operations backed by a local LLM served through Ollama.
 */
@RestController
@RequestMapping("/api/v1/chat")
@RequiredArgsConstructor
public class ChatController {

    private final ChatService chatService;

    /**
     * Receives a question and returns the answer generated by the LLM.
     *
     * @param request the question payload
     * @return 200 OK with the generated answer
     */
    @PostMapping
    public ResponseEntity<ChatResponse> ask(@Valid @RequestBody ChatRequest request) {
        ChatResponse response = chatService.ask(request);
        return ResponseEntity.ok(response);
    }

}
